# Use official Node.js image
FROM node:18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json* ./

RUN npm install

# Copy app source code
COPY . .

# Start the app
CMD ["npm","run", "start"]
